[package]
name = "phase-finance"
authors = ["njerschow <nj18@nyu.edu>", "j0nl1 <jonlitech@gmail.com>"]
version = "0.1.0"
edition = "2018"

[dependencies]
cosmwasm-std = "1.1.5"
cw-utils = "1.0.1"
cosmwasm-schema = { version = "1.1.5" }
thiserror = { version = "1.0.26" }

[profile.release]
overflow-checks = true